version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: urbix-postgres
    environment:
      POSTGRES_DB: urbix
      POSTGRES_USER: urbix
      POSTGRES_PASSWORD: urbix
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7.2
    container_name: urbix-redis
    ports: ["6379:6379"]

volumes:
  pgdata:
